#define STEAM_ID_MAGNETAR 12345
#define STEAM_ID_JUANMA   76561198057729934
#define STEAM_ID_VARIAS   12345
#define STEAM_ID_MAUR     12345

enableDebugConsole[] = {
    QUOTE(STEAM_ID_MAGNETAR),
    QUOTE(STEAM_ID_JUANMA),
    QUOTE(STEAM_ID_MAUR),
    QUOTE(STEAM_ID_VARIAS)
};

cba_settings_whitelist[] = {
    QUOTE(STEAM_ID_MAGNETAR),
    QUOTE(STEAM_ID_JUANMA),
    QUOTE(STEAM_ID_MAUR),
    QUOTE(STEAM_ID_VARIAS)
};
