PREP(addAllowedPlayer);
PREP(checkAllowedPlayers);
PREP(handleAllowTeleport);
PREP(retrievePlayerVariables);
PREP(retrieveStatus);
PREP(savePlayerVariables);
PREP(saveStatus);
PREP(saveStatusAdvancedFatigue);
PREP(teleport);
